### ISSUE TITLE
Too short period of time provided as input for MAJA

### ISSUE THREAD

**Issue by seffinier** [CNES/Start-MAJA#20]
Hello,

I installed MAJA 3.3.0 TM with Start_maja on a CentOS 7.6 but the result I get (without errors) is of a much lower definition than what is downloadable from https://theia.cnes.fr/atdistrib/rocket/#/home. 

One of the masks downloaded from theia's site (converted to jpg because I can not attach a tif)
![SENTINEL2A_20190516-105713-915_L2A_T31UER_C_V2-1_CLM_R1](https://user-images.githubusercontent.com/9048638/59088988-55e08800-8909-11e9-9aad-d0d18cd36de2.jpg)

The corresponding mask I generated
![SENTINEL2A_20190516-105713-915_L2A_T31UER_C_V1-0_CLM_R1](https://user-images.githubusercontent.com/9048638/59088990-56791e80-8909-11e9-9d06-91d9d5e8d357.jpg)

Can anyone tell me in which direction I should look ?

Thanks !

My configuration:
- Python 2.7
- GDAL 2.4
- Maja 3.3.0 TM
- GIPP_MAJA_S2A_S2B_TM downloaded from http://tully.ups-tlse.fr/olivier/gipp_maja/tree/master/GIPP_S2_MAJA_3.3_TM
- LUT_MAJA_S2A_S2B_CAMS_H2ONew_20190411 downloaded from https://zenodo.org/record/2636694#.XOzwMlUzZUQ
- DTM generated with the commande "python DTMCreation.py -k /DATA/tmp/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml -g 31UER -s /DATA/tmp/ -w /DATA/tmp/ -o /DATA/tmp/dtm/31UER"
- S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml downloaded from https://sentinel.esa.int/documents/247904/1955685/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
- SRTM downloaded from http://srtm.csi.cgiar.org/srtmdata/
- SWBD downloaded from https://earthexplorer.usgs.gov/

Commande is: "python ./start_maja.py -f folders.txt -g GIPP_MAJA_S2A_S2B_TM -l
LUT_MAJA_S2A_S2B_CAMS_H2ONew_20190411 -t 31UER -s Wallonie -d 20190506 -e
20190516"

**Comment by olivierhagolle** [comment]
Hi Sébastien
I think I have a clue, thanks to the command line.

MAJA is a multi-temporal method. The more data it uses the more accurate it gets.
It turns out you provided a working period of 10 days, so at best, MAJA had 3 or 4 images as input. Knowing the usual cloud cover in Wallonie, this would make only 1 or 2 cloud free observations. With such a short period, the multi-temporal method is not efficient, and you get only the results of the mono-temporal method.

I guess the results would be much better with  -d 20190401 -e 20190610, for instance. Of course, it means you have to download all the L1C products in that period.
Could you please try that ?
Thanks,
Olivier

**Comment by seffinier** [comment]
ok, I will try on a longer period and keep you posted
Thanks !

**Comment by seffinier** [comment]
Using a longer period (20190313 to 20190611) is indeed improving a lot the results (not exactly the same but close enough)
![SENTINEL2A_20190516-105713-915_L2A_T31UER_C_V1-0_CLM_R1](https://user-images.githubusercontent.com/9048638/59410346-ec54f380-8db8-11e9-9b8d-2c147d64055d.jpg)

And indeed, over that almost 3-month period I get only 17 valid results out of the 53 products for the 3 orbits going over that tile...

By the way, I adapted slightly the scripts to be able to use Python 3.5 (changed the call to file() into calls to open() in start_maja.py and added the parenthesis to the print calls in convert_CAMS_DBL.py)

Thanks a lot
