### ISSUE TITLE
SRTM download link doesn't respond 

### ISSUE THREAD

**Issue by rohitshetty** [CNES/Start-MAJA#90]
Hi, 
SRTM.py inside `StartMaja/prepare_mnt/mnt` folder uses `https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/%s.zip` to download SRTM files. 
But SRTM download link has been not responsive. 
Example: https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_17_05.zip

There were some similar errors a few months back, where a new change was merged to Maja changing HTTP to HTTPS which fixed this. 
Is this some similar error too?

**Comment by olivierhagolle** [comment]
Hi, I just tried  https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_17_05.zip from my navigator and it worked. Was it a temporary issue on the server ?
Olivier

**Comment by petket-5** [comment]
There seem to be some downtimes associated to the SRTM data. Depending on where you want to process Maja, you might want to switch over to [EuDEM v1.1](https://land.copernicus.eu/imagery-in-situ/eu-dem/eu-dem-v1.1), also supported by Maja since v4.2 which covers the entirety of Europe.
Unfortuntely we cannot host a backup of SRTM data, which would be too costly for us. So if you are relying on it, the only solution is to wait until the server is up again.

Kind regards,
Peter

**Comment by rohitshetty** [comment]
Thank you @olivierhagolle and @petket-5, 

I tried loading the srtm_17_05.zip and it still fails. 
I'll try soon to run this on server in a different location and see if it is my network. 

@petket-5 
Is it feasible if someone wants to host srtm data themselves for internal use? If yes can you please point me to any pointers?

Thanks a lot for the reply and appreciate all the efforts you guys put into :)

**Comment by rohitshetty** [comment]
I tried this on the server and was able to wget it manually, and also some of the MAJA processes ran successfully. So I think it is something with my network as locally I still cannot wget it. 

Sorry for the false alarm.

**Comment by olivierhagolle** [comment]
Thanks for letting us know !
